name: Run UI + API Tests for rr

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Installing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run Tests and Generate HTML Report
        run: |
          mkdir -p reports
          pytest --html=reports/report.html --self-contained-html --capture=tee-sys || true
        continue-on-error: true
  
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/
