name: Run UI + API Tests for rr

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Installing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

    # Step 4: Run tests and generate Allure results
      - name: Run Pytest
        run: |
          mkdir -p reports/allure-results
          pytest --alluredir=reports/allure-results --capture=tee-sys || true
        continue-on-error: true  # ensures workflow continues even if tests fail
    
      # Step 5: Generate Allure report
      - name: Generate Allure Report
        run: |
          pip install allure-commandline
          allure generate reports/allure-results -o reports/allure-report --clean || true
    
      # Step 6: Archive Allure report as artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: reports/allure-report
